### ISSUE TITLE
Event not updating on Android.

### ISSUE THREAD

**Issue by needledrag** [jfversluis/Plugin.Maui.CalendarStore#33]
Hi,

I've been able to add and query events but when updating an event, I query the timespan to get the event, the event comes back with the eventId and then I update it using UpdateEvent using the eventId I just received, however it doesn't update the device calendar.  I noticed we're not passing through a calendarId on the update, is this missing or should the device calendar be able to update with just the eventId?

Regards
Shaun

**Comment by jfversluis** [comment]
Is this on Android? On Android it seems to sometimes take a little while to sync, not sure why. Could you confirm that if you do this and you wait a few seconds or maybe minutes that it does show up?

**Comment by needledrag** [comment]
Yes it was Android, Google calendar.  I've noticed the slight lag in time, perhaps because it's syncing with the account but it still didn't show the updates 20 min later.  I didn't get an error either so not sure what it is.

**Comment by jfversluis** [comment]
Would you be able to provide some more details? What is the code you're using for this? What Android version?

**Comment by needledrag** [comment]
Android 13 (API33), Pixel 5 & 6 emulator


`// find old event, get eventId and use it to update event with new details, if no event found, add it
var oldEvents = await GetAppointments(calendarId, startDt, endDt);

var oldEvent = oldEvents?.First(x => x.Description.Contains(Helpers.AppPreferences.DeviceCalendarIdentifier));

// add event if we can't find it
if (oldEvent is null)
{
	await CreateEvent(calendarId, title, SetIdentifier(desc), location, startDt, endDt, false);
	return true;
}

await CalendarStore.Default.UpdateEvent(oldEvent.DeviceEventId, title, SetIdentifier(desc), location, startDt, endDt, isAllDay);
return true;`

As mentioned, everything works, it finds the event, is able to add it if there is no event etc... but using the eventId returned and new details, it doesn't update.

// edit update

I've also tried to  use the CalendarEvent class to pass in the event to update as an object because it has the calendarId in it, but only eventId, calendarId and Title are able to be set, can't use the object to change a start/end date or description.

I've tried updating using the CalendarEvent object with only the eventId, calendarId and a new title and just updating that but still no update showing.

// further update
UpdateEvent seems to work fine on iOS testing using iOS 16.2, iPhone14 Pro, so it's just Android

**Comment by jfversluis** [comment]
Great investigation and narrowing it down to it only not working on Android, thanks!

Sorry, it's probably me, but I still don't have really clear what is the thing that is not working. I see you say

> but using the eventId returned and new details, it doesn't update.

But I don't really see the code for that, right?

What is the path that doesn't work on Android? Is it this line: `await CalendarStore.Default.UpdateEvent(oldEvent.DeviceEventId, title, SetIdentifier(desc), location, startDt, endDt, isAllDay);`?

So when it _does_ find `oldEvent` and it goes to `UpdateEvent`, then it doesn't update but only on Android, correct?

In either case, maybe it's useful to have a look at the sample in this repo and see what the difference is with your project: https://github.com/jfversluis/Plugin.Maui.CalendarStore/blob/main/samples/Plugin.Maui.CalendarStore.Sample/AddEventsPage.xaml.cs#L101

Because as far as I know this works

**Comment by needledrag** [comment]
Yeah, so the UpdateEvent doesn't update on Android with a valid eventId.  If you just send in a CalendarEvent object to the update with, calendarId, eventId and Title, it doesn't update either.

I've been browsing the source to see if I was doing something wrong but couldn't find any discrepancies.  Same code works on iOS.  I'll have another look though.  Thanks.

**Comment by jfversluis** [comment]
OK perfect! Then at least we're on the same page on what is going wrong 😄 thank you for your patience here.

There might as well be a bug there, I'm in doubt now if I have actually seen it working on Android in my sample app. I'm pretty sure I did, but now I'm not sure. So if you want to test some more you might want to try the sample app and see if it works there. If it does, it could be something in your code. If it doesn't work, then it's something in the library code.

**Comment by needledrag** [comment]
I ran the sample app and it wasn't updating either.
I'm not that familiar with how the android calendar works but scratching around  CalendarStore.android.cs it seems the UpdateEvent cursor is reading from the calendarTableUri and using the calendarColumns array to identify the column.  
Then it reads the cursor in a loop and reads from that cursor but it seems to be reading the calendar id not the event id which is why for me it never finds the platformEventId and doesn't meet the requirement to update so it falls through without error and says it's updated.

I changed the calendarsTableUri to eventsTableUri and replaced the calendarColumns array with eventsColumns array and it updated.  It probably worked in testing because the calendar id matched an event id when the event id was low?  Again I'm not that familiar with the android calendar so I may be wrong here but it definitely updated the device calendar when I changed it.

https://github.com/jfversluis/Plugin.Maui.CalendarStore/blob/6daabb865c1a03d59ba118e4937e15fdd5603b80/src/Plugin.Maui.CalendarStore/CalendarStore.android.cs#L340

**Comment by jfversluis** [comment]
You are absolutely right! Wrong URL and not great error checking, or at least not surfacing. Fixed all of that in the linked PR so I will merge that and release a new version so you can test that. Please let me know how that goes!

**Comment by needledrag** [comment]
Thanks, android update is working although there's an issue with CreateEvent now 
Cannot access a disposed object.
Object name: 'Android.Database.CrossProcessCursorWrapper'.

But can update an existing event now.

**Comment by jfversluis** [comment]
Haha noooooo! Alright, thanks! Maybe I was a bit too rigorous with the refactoring. 

I'll have a look at that one tomorrow!

Thanks for all the testing! Appreciate it!

**Comment by needledrag** [comment]
If it helps any, I removed the 'using' from the GetPlatformCalendar method on the cursor as it seems it was causing the Disposal of the object when it was passed to the CreateEvent (which was also declaring the returned object with 'using' for the cursor), so possibly this is causing it?  Also commented out the cursor.MoveToNext() in the same method (GetPlatformCalendar) as it ended up with the cursor moving past the current calendar record and not setting the platformCalendarId.  Seems to work on the CreateEvent and UpdateEvent now although I'd probably check this is what was causing it and not going against anything intended.


https://github.com/jfversluis/Plugin.Maui.CalendarStore/blob/d628b7aa80d08c37216b479a76e14f6ff0533e9f/src/Plugin.Maui.CalendarStore/CalendarStore.android.cs#L471

**Comment by jfversluis** [comment]
@needledrag New release is going out now with which everything should work again 😄 as a bonus now all create events return the newly created ID.

Let me know if there is anything else or features that you'd like to see. Again, thanks for all the cooperation here!

**Comment by needledrag** [comment]
Thank you, works a treat, and the returned id is really helpful, so is the plugin, cheers.
