### ISSUE TITLE
EventId returned from adding a new item to the calendar doesn't match eventId returned from query

### ISSUE THREAD

**Issue by needledrag** [jfversluis/Plugin.Maui.CalendarStore#37]
I've been storing the returned eventId from newly created events and use them to filter out the corresponding calendar event or use it when updating the event.

For Android this works a treat but for iOS the eventId returned when creating an event on the device calendar is not the same as the eventId when querying an event from the device calendar.

Example : eventId returned from adding an event to the calendar : 
0BB924BC-AB6C-4199-B014-908638021287:533C9356-144E-4596-AF50-9BC06660505A

eventId for that event when querying the calendar : 
A7158E14-1875-4BD5-A6E5-90A2B7AB1FBD

Initially I thought it was the calendar Id and event Id returned from adding an event but it's neither.  This is on iOS only (iPhone 14 iOS 16.2)

Any help would be appreciated.

Regards

**Comment by jfversluis** [comment]
Oh that's interesting, thanks for letting me know, I'll have a look!

**Comment by jfversluis** [comment]
Found it, returning the wrong ID from the iOS/macOS code

**Comment by needledrag** [comment]
Amazing, thank you, all working great now.
