### ISSUE TITLE
The event time is 2 hours behind

### ISSUE THREAD

**Issue by geertgeerits** [jfversluis/Plugin.Maui.CalendarStore#4]
Hi, thanks for this plugin.
When I run 'MauiCalendarStorePluginSample' on my Samsung S21 Android 13, the event time is 2 hours behind.
I get: 06/09/2023 17:00:00 +00:00 but the start time should be 19:00:00, this is true for all events.
On Windows it works correctly (06/09/2023 19:00:00 +02:00).
How can this be solved? Thank you in advance.

**Comment by geertgeerits** [comment]
Here's a workaround. I don't know if this is the ideal solution. Tested in Windows 11 and Android 13.
_________________________________________________________________________________________________________
using Plugin.Maui.CalendarStore;
using System.Globalization;

namespace MauiCalendarStorePluginSample
{
    public partial class MainPage : ContentPage
    {
        private string cDateFormat = "";

        public MainPage()
        {
            InitializeComponent();

            // Get the system date format and set the date format.
            cDateFormat = CultureInfo.CurrentCulture.DateTimeFormat.ShortDatePattern;
        }

        private async void OnCounterClicked(object sender, EventArgs e)
        {
            var calendars = await CalendarStore.Default.GetCalendars();

            foreach (var calendar in calendars)
            {
                await DisplayAlert("Calendars", $"{calendar.Name} ({calendar.Id})", "OK");
            }

            var events = await CalendarStore.Default.GetEvents(startDate: DateTimeOffset.Now.AddDays(-1), endDate: DateTimeOffset.Now.AddDays(10));

            string cCalendarEvents = "";
            string cStartDate;
            DateTime dStartDate;

            foreach (CalendarEvent ev in events)
            {
                if (Convert.ToString(ev.StartDate).Contains("+00:00"))
                {
                    dStartDate = DateTime.Parse(Convert.ToString(ev.StartDate));
                    cStartDate = dStartDate.ToString(cDateFormat + " HH:mm zzz");
                    cCalendarEvents = $"{cCalendarEvents}{cStartDate}, {ev.Title}\n";
                }
                else
                {
                    cCalendarEvents = $"{cCalendarEvents}{ev.StartDate}, {ev.Title}\n";
                }
            }

            await DisplayAlert("Events", cCalendarEvents, "OK");
        }
    }
}
_________________________________________________________________________________________________________

**Comment by jfversluis** [comment]
~Hm interesting. Do you have any settings for a timezone in your Calendar app on Android by any chance? Or on your Google account, if this data is coming from there? Is your device set to the right timezone?~

O yeah I can see this happening. Seems we need to retrieve the timezone information manually and apply it for Android.

**Comment by jfversluis** [comment]
@geertgeerits preview 2 should be going out in minutes, please try that one and see if that fixes it. Thanks!

**Comment by geertgeerits** [comment]
Thanks for the quick solution. The time is now correct.
