### ISSUE TITLE
Unable to create a calendar after checking by name if the calendar does not exist

### ISSUE THREAD

**Issue by angoudjou** [jfversluis/Plugin.Maui.CalendarStore#42]
Hi,
I tried to create a calendar only if it doest not exist.
When I do so I have the following error message on windows : Access is denied. (Ox80070005 (E_ACCESSDENIED))
However it works on Android plateform. here is my code .
Thanks for your help

##code##
async void GetCalorCreate()
{
    try
    {

        string calName = "c1";
        var cl = await CalendarStore.Default.GetCalendars();
        if (!cl.Any(c => c.Name == calName))
        {
            var t = await CalendarStore.Default.CreateCalendar(calName);
                            }
    }
    catch (Exception ex)
    {

        await DisplayAlert("Alert", ex.Message, "ok");
    }

}

**Comment by jfversluis** [comment]
Thanks for the report! This should be fixed with the next release!
