### ISSUE TITLE
System.ObjectDisposedException Thrown When Awaiting CalendarStore.Default.GetCalendar(Id)

### ISSUE THREAD

**Issue by vikher** [jfversluis/Plugin.Maui.CalendarStore#48]
Bug Description:

When attempting to retrieve a specific calendar from an Android device using the CalendarStore.Default.GetCalendar(Id) method after retrieving all calendars and storing the ID of the first one, a {System.ObjectDisposedException} is thrown. The exception specifically points to 'Android.Database.CrossProcessCursorWrapper'.

Environment:

Platform: Android API 33
.NET Versions: 7.0.96
MAUI

Steps to Reproduce:

1. Retrieve all calendars using CalendarStore.Default.GetCalendars().
2. Store the ID of the first calendar from the retrieved list.
3. Attempt to get the specific calendar using CalendarStore.Default.GetCalendar() with the stored ID.

Expected Behavior:
The GetCalendar() method should successfully retrieve the specific calendar based on the provided ID without throwing any exceptions.

Actual Behavior:
A {System.ObjectDisposedException} occurs, indicating:
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Android.Database.CrossProcessCursorWrapper'.
   at Java.Interop.JniPeerMembers.AssertSelf(IJavaPeerable self) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Jav…

Code Snippet:
```
var crossCalendars = await CalendarStore.Default.GetCalendars();

Calendar firstCalendar = crossCalendars.ElementAt(0);

string firstCalendarId = firstCalendar.Id;

var selectedCalendar = await CalendarStore.Default.GetCalendar(firstCalendarId);

```

<img width="814" alt="crash" src="https://github.com/jfversluis/Plugin.Maui.CalendarStore/assets/3643619/e4d5615a-7b20-4c04-9c0f-e5f35cb41889">
<img width="1028" alt="crash2" src="https://github.com/jfversluis/Plugin.Maui.CalendarStore/assets/3643619/499a4ae2-d223-40e2-a6d1-cf7c76867cd7">

**Comment by erikbusker** [comment]
I can confirm I get the same exception. Happens anytime when I use GetCalendar();

If I get all calendars first it works fine as a simple workaround
` var allCalendars = await _calendarStore.GetCalendars();`
`Calendar calendar = allCalendars.FirstOrDefault(c => c.Id == calendarId);`
