### ISSUE TITLE
Update README with latest iOS/macOS information

### ISSUE THREAD

**Issue by jfversluis** [jfversluis/Plugin.Maui.CalendarStore#49]
iOS & macOS need new info.plist entries. MacOS also needs a entry in the entitlements.plist for sandboxed apps.

This needs to be added to the README.

**Comment by geertgeerits** [comment]
An app was rejected in the app store with just this in the Info.plist file:
```
<key>NSCalendarsUsageDescription</key>
<string>This app wants to access your calendars</string>

```
You must state which data is retrieved and why, such as this, for example:
```
<key>NSCalendarsUsageDescription</key>
<string>This app needs your permission to read events from your calendars. It concerns the date, time and title of the event.</string>

<key>NSCalendarsFullAccessUsageDescription</key>
<string>This app needs your permission to read events from your calendars. It concerns the date, time and title of the event.</string>

```

**Comment by jfversluis** [comment]
Thank you for the addition, however this will be pretty hard to describe. The review process at Apple has known to be very strict, but also at times random depending on who is looking at your app version. I'll see if I can add a note about it, but typically just make sure that all of your keys, not just the ones for the calendar, are descriptive and state why you want a certain permission and what you will do with it.
