### ISSUE TITLE
The event time is 2 hours behind also on iOS

### ISSUE THREAD

**Issue by geertgeerits** [jfversluis/Plugin.Maui.CalendarStore#6]
Hi,
When I test my app using the 'Plugin.Maui.CalendarStore version 1.0.0-preview2' on an iPhone 7 iOS 15.7.7 and an iPad 8 generation iOS 16.6, the event time is also 2 hours behind (same on 'MauiCalendarStorePluginSample').
On Windows and Android it works correctly.
Thank you in advance.

**Comment by jfversluis** [comment]
Preview 3 is rolling out right now which should fix this, please let me know if it did or didn't!

**Comment by geertgeerits** [comment]
Hi Gerald,

The birthdays are still 2 hours behind.
ex. 13/09/2023 22:00 must be 14/09/2023 00:00.

Best regards, Geert

**Comment by jfversluis** [comment]
Just to be clear: you mean just birthdays? How did you add those to your calendar? By creating a birthday on one of your contacts? The rest of the events work?

**Comment by geertgeerits** [comment]
Hi,

Not only birthdays but also other events that start at 00:00 h.
Birthdays that were created in the calendar and/or in the contacts do have that problem.
In Windows and Android all hours are correct.

**Comment by jfversluis** [comment]
So, events that start at midnight, other events do show the right time?

**Comment by geertgeerits** [comment]
Yes that is correct.
Before preview 3, all times were wrong in iOS.

**Comment by jfversluis** [comment]
Try preview 4 that is currently underway please!

**Comment by geertgeerits** [comment]
Thanks for the update.  All times are correct.
